### PR TITLE
Fix plugin channel failure to communicate with Spigots (register channel)

### PR DESCRIPTION
**Pull request by Bunnui**
**I have poor English, so I use machine translation.**

After many tests, it was determined that syncmatica did not register the channel in CustomPayloadC2SPacket, resulting in the inability to communicate with the plug-in channel on bukkit. In the https://wiki.vg/Plugin_channels#Reserved_channels, you can see that there is a Reserved with the 'minecraft:register' identifier, and when the server registers the plug-in channel, the client also registers, otherwise the client cannot receive the plug-in channel identifier

**the original**
经过多次测试，可以确定的是syncmatica 在 CustomPayloadC2SPacket 没有进行通道的注册，导致在bukkit上，无法使用插件通道进行通讯。 在https://wiki.vg/Plugin_channels#Reserved_channels 可以看见有 Reserved ，其中有 `minecraft:register` 标识符，服务端进行注册插件通道的时候，客户端也进行注册，否则客户端无法接收到插件通道的标识符

### CODE REVIEW

**Comment by Bunnui** [comment]
This is a modified test

**Comment by Bunnui** [comment]
Found some issues

**Comment by nnnik** [comment]
Hi thank you. I never knew of this mechanic. I generally have a few questions regarding this PR:
A) Since I prevent all other mods from handling minecraft:register (due to the nature of the CommunicationManager catching all packets related to syncmatica) won't that create an incompatability with all other mods that rely on sending this packet?
B) Will the server properly handle multiple minecraft:register responses from the client? (The link you provided seems to suggest so)
C) Is this only required since 1.20?

**Comment by Bunnui** [comment]
> Hi thank you. I never knew of this mechanic. I generally have a few questions regarding this PR: A) Since I prevent all other mods from handling minecraft:register (due to the nature of the CommunicationManager catching all packets related to syncmatica) won't that create an incompatability with all other mods that rely on sending this packet? B) Will the server properly handle multiple minecraft:register responses from the client? (The link you provided seems to suggest so) C) Is this only required since 1.20?

### My English is very poor, so I used machine translation. If you look strange, please forgive me!

Sorry, I didn't see a reply before.

I found that the problem would enter an infinite loop, so I deleted this branch and fixed it.

Currently I set the MixinClientPlayNetworkHandler through the @Mixin, MixinServerPlayNetworkHandler priority, because I found that if the fabric API mod is loaded, it will intercept the registration identifier, resulting in the failure to receive it normally. '@Mixin(value = ClientPlayNetworkHandler.class, priority = 998) fabric API priority = 999, normal = 1000' 

Then I simply wrote channel management so that the registered ones are not sending and avoiding sending each other into a closed loop.

I'm working with each other for now, but it's not clear if there's any undiscovered bugs




https://github.com/Bunnui/fabric-syncmatica
https://github.com/Bunnui/bukkit-syncmatica

The plugin has been implemented, because the original author did not register the plugin channel, so it cannot communicate with the plugin channel, which is the branch I modified.

Note: I don't know if there is an error!! Currently the test is up and running.

Attach the test file

[syncmatica-1.20.1-0.3.10.zip](https://github.com/End-Tech/syncmatica/files/12515606/syncmatica-1.20.1-0.3.10.zip)

**Comment by Bunnui** [comment]
QQ截图20230905020932

顺便说一下，我目前的分支修改情况并没有垄断渠道。我将复制一份数据以供阅读。在我完成处理后，mod没有取消操作，注册的标识符仍将传递给fabric API。在结构API上，它将阻止此标识符。当mod在结构API中处于低级别时，它将不会接收到注册的标识符

**Comment by Bunnui** [comment]
Also, I have some small suggestions
1. I hope to encapsulate the data type of the protocol (channel) into an abstract type that provides methods for reading and writing. Then, different types of data packets inherit it, and when there are reads and writes, directly call the methods in the class. This way, the readability is better and there is no need to be squeezed into one class. At present, the reading and writing methods are all in the same class, making it difficult to read code.
2. The processing of channel types should preferably be done together, using specialized packet type classes for reading and writing based on the type.
When I was reading the source code, I was jumping back and forth, causing a bit of confusion. I had to copy the source code to the Bukkit for editing and fine-tuning

**Comment by nnnik** [comment]
> Also, I have some small suggestions
> 
> 1. I hope to encapsulate the data type of the protocol (channel) into an abstract type that provides methods for reading and writing. Then, different types of data packets inherit it, and when there are reads and writes, directly call the methods in the class. This way, the readability is better and there is no need to be squeezed into one class. At present, the reading and writing methods are all in the same class, making it difficult to read code.
> 2. The processing of channel types should preferably be done together, using specialized packet type classes for reading and writing based on the type.
> 
> When I was reading the source code, I was jumping back and forth, causing a bit of confusion. I had to copy the source code to the Bukkit for editing and fine-tuning

1. seems like a good idea. I'm sure I misunderstand 2. It seems like wth 2 you are suggesting to put all the Exchanges in one class which would directly contradict your suggestion from point 1.

**Comment by Bunnui** [comment]
This is the class of the initial concept of the item

```java
public abstract class ProtocolChannelPacket {
    public final Identifier channel;
    public final ProtocolPacket data;

    public ProtocolChannelPacket(Identifier channel, ProtocolPacket data) {
        this.channel = channel;
        this.data = data;
    }
}
```

```java
public abstract class ProtocolPacket {

    public abstract void read(PacketByteBuf byteBuf);

    public abstract void write(PacketByteBuf byteBuf);

    public abstract void handle(Context context, ExchangeTarget exchangeTarget, PacketByteBuf byteBuf);
}

```

```java

public class HandshakePacket extends ProtocolPacket {
    public String version;

    protected HandshakePacket(String version) {
        this.version = version;
    }

    public HandshakePacket(PacketByteBuf byteBuf) {
        read(byteBuf);
    }

    @Override
    public void read(PacketByteBuf byteBuf) {
        this.version = byteBuf.readString();
    }

    @Override
    public void write(PacketByteBuf byteBuf) {
        byteBuf.writeString(this.version);
    }

    @Override
    public void handle(Context context, ExchangeTarget exchangeTarget,PacketByteBuf byteBuf) {
        // Business processing
    }
}

```


```java
public class ProtocolHandle {
    public static final Identifier HANDSHAKE = new Identifier("syncmatica:register_version");

    public static final Map<Identifier, Class<? extends ProtocolPacket>> packets = new HashMap<>();

    static {
        registers();
    }

    public static void registers() {
        packets.put(HANDSHAKE, HandshakePacket.class);
    }

    public void receive(Context context, ExchangeTarget exchangeTarget, Identifier channel, PacketByteBuf data) {
        if (packets.containsKey(channel)) {
            Class<? extends ProtocolPacket> aClass = packets.get(channel);
            try {
                ProtocolPacket protocolPacket = aClass.getDeclaredConstructor().newInstance();
                protocolPacket.handle(context, exchangeTarget, data);
            } catch (Exception ignored) {
            }
        }
    }

    public void send(Context context, ExchangeTarget exchangeTarget, ProtocolChannelPacket packet) {
        PacketByteBuf byteBuf = new PacketByteBuf(Unpooled.buffer());
        packet.data.write(byteBuf);
        exchangeTarget.sendPacket(packet.channel, byteBuf, context);
    }
}

```

**Pull request closed without merging**
