### PR TITLE
Fix channel

### PR DESCRIPTION
**Pull request by Bunnui**

### CODE REVIEW

**Comment by Bunnui** [comment]
Previously, I submitted many unrelated modifications, but now I am modifying them again and forcing them to overwrite the push. This time, only channel related content is available

**Comment by sakura-ryoko** [comment]
Does this code work for 1.20.2 ?

**Comment by Bunnui** [comment]
> Does this code work for 1.20.2 ? (After porting the version #, etc) ?

If the original source code of Minecraft hasn't changed significantly, it should be compatible after porting the version number.

**Comment by Bunnui** [comment]
I'll try it out when I have time.

**Pull request merged**
