### PR TITLE
1.20.2

### PR DESCRIPTION
**Pull request by s-yh-china**
not best, but can work

### CODE REVIEW

**Comment by sakura-ryoko** [comment]
I was tinkering with something similar (not working but more complicated), and merging this with the Bunni code (ChannelManager), and came to a similar conclusion since they changed the CustomPayload api, at least.

**Comment by s-yh-china** [comment]
> I was tinkering with something similar (not working but more complicated), and merging this with the Bunni code (ChannelManager), and came to a similar conclusion since they changed the CustomPayload api, at least.

I think the network system should eventually be completely modified, but I dont have time to do this. the current solution can at least use XD

**Comment by sakura-ryoko** [comment]
I'll build and test it in my test environment server, thank you.  I really don't know Java, so my attempts have failed mostly.

**Comment by sakura-ryoko** [comment]
You are correct my friend!  Thank you so much!  It works!  I am seeing the Debug packets fly by and functional, besides the outstanding litematica based errors (ha)
@nnnik -- BUMP for you to manage when you get to it!
(Also he would need to update the README & version # from 0.3.11 )

**Comment by nnnik** [comment]
Wouldn't this remove the feature to run syncmatica in singleplayer or am I reading this wrong?

**Comment by sakura-ryoko** [comment]
I'd say test it?  I'm not sure about the functionality of Syncmatica for single player ?

**Comment by nnnik** [comment]
Syncmatica also works in singleplayer worlds. This is helpful if you open your world to LAN for example.
That's why ServerMixin etc. was also applied on the client.
I will try it out but given the information presented I think this will remove that functionality from syncmatica.

**Pull request merged**
