### PR TITLE
Update to 1.19.1

### PR DESCRIPTION
**Pull request by kosma**
Updated to official 1.19.1. As usual, barely tested. :D

Remember to change target branch to 1.19.

### CODE REVIEW

**Comment by wearfa** [comment]
1.19plz

**Comment by kosma** [comment]
Hi, what happened to this mod's author? Are you ok?

**Comment by nnnik** [comment]
I really don't want to maintain a third version of this mod for every single version going forward - I'd really rather just remove the feature than go ahead with this implementation.

**Comment by kosma** [comment]
Can you elaborate on that comment?
Also, this PR is pretty old, no idea if it's still relevant.

**Comment by nnnik** [comment]
I target all minecraft versions - I do so by rebasing the branches manually.
I would have to do this for this branch as well. 
The feature in question is also only useful when really old versions of syncmatica (0.1.1<=) encounter newer versions.

But I think I can accept this fix for the base branch and then forward everything.

**Comment by kosma** [comment]
You can do whatever you want with this PR, as long as some 1.19.2 version is available I don't really have much of an opinion. I made this because me and my friends needed it, this is by no means something of high quality or anything - just a quick and dirty PR. So feel free to close and do 1.19.2 support your own way. :)

**Pull request merged**
